name: CI/CD Deployment

on:
  push:
    branches:
      - main # Deploy on push to 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "node" # Use the latest Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React App
        env:
          CI: false # Disables treating warnings as errors in production builds
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }} # GitHub token for deployment
          publish_dir: ./build # Directory containing the production build
